# Generated by Django 5.1.2 on 2026-06-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pics/', verbose_name='Profile Picture (Student Upload)'),
        ),
    ]
