# Generated by Django 5.2.8 on 2025-11-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_lecture_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='topic',
            field=models.CharField(default='Unspecified Topic', max_length=200, verbose_name='Lecture Topic'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lectures', to='doctors.group', verbose_name='Group'),
        ),
    ]
