# Generated by Django 5.2.8 on 2025-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_lecture_topic_alter_lecture_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='doctors.group', verbose_name='Enrolled Groups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='University ID'),
        ),
    ]
